import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import ReduxProvider from "@/redux/ReduxProvider";
import { UiLayout } from "./UiLayout";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Care Consult",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className} style={{ background: "#E2F5F5" }}>
        <UiLayout>
          <ReduxProvider>{children}</ReduxProvider>
        </UiLayout>
      </body>
    </html>
  );
}
